name: Build Canary Image

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to build'
        required: true

##
# Invoke:
#   gh workflow run "Build Prerelease Image" -f tag=2.0.0-canary.0
##

permissions:
  contents: read
  packages: write

env:
  IMAGE_NAME: litehex/torproxy
  IMAGE_TAG: ${{ github.event.inputs.tag }}
  BUILD_PLATFORMS: linux/amd64,linux/arm64

jobs:
  dckr-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          platforms: ${{ env.BUILD_PLATFORMS }}
          tags: docker.io/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}

