name: Release Docker Image

on:
  release:
    types: [ published ]

jobs:
  push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    env:
      IMAGE_NAME: litehex/torproxy

    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push to Docker Registry
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: docker.io/${{ env.IMAGE_NAME }}:${{ github.ref }}

      - name: Add latest tag
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          docker tag ${IMAGE_NAME}:${{ github.ref }} ${IMAGE_NAME}:latest
          docker push ${IMAGE_NAME}:latest
